// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs har-viewer`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "hex-viewer",
    "icon": "🔍",
    "name": {
      "en": "Hex Viewer",
      "ja": "Hex Viewer",
      "zh": "Hex Viewer",
      "de": "Hex Viewer",
      "es": "Hex Viewer"
    },
    "desc": {
      "en": "Inspect any file as a hex dump, right in your browser.",
      "ja": "どんなファイルもブラウザで 16 進ダンプとして表示。",
      "zh": "在浏览器中把任意文件显示为十六进制内容。",
      "de": "Beliebige Dateien im Browser als Hex-Dump ansehen.",
      "es": "Ver cualquier archivo como volcado hexadecimal en tu navegador."
    }
  },
  {
    "slug": "strip-tracking",
    "icon": "🧹",
    "name": {
      "en": "Strip Tracking Params",
      "ja": "URLトラッキング除去",
      "zh": "移除追踪参数",
      "de": "Tracking-Parameter entfernen",
      "es": "Eliminar parámetros de rastreo"
    },
    "desc": {
      "en": "Remove UTM/fbclid/gclid and other tracking params from a URL.",
      "ja": "URLからUTM/fbclid/gclidなどのトラッキングパラメータを除去。",
      "zh": "从网址中移除 UTM/fbclid/gclid 等追踪参数。",
      "de": "Entferne UTM/fbclid/gclid und andere Tracking-Parameter aus einer URL.",
      "es": "Elimina UTM/fbclid/gclid y otros parámetros de rastreo de una URL."
    }
  },
  {
    "slug": "identify-file",
    "icon": "🔎",
    "name": {
      "en": "Identify File Type",
      "ja": "ファイル形式判定",
      "zh": "识别文件类型",
      "de": "Dateityp erkennen",
      "es": "Identificar tipo de archivo"
    },
    "desc": {
      "en": "Detect a file's real type from its binary signature, not its extension.",
      "ja": "拡張子ではなくバイナリシグネチャからファイルの本当の種類を判定。",
      "zh": "根据二进制签名而非扩展名识别文件的真实类型。",
      "de": "Erkennt den echten Dateityp anhand der Binärsignatur, nicht der Erweiterung.",
      "es": "Detecta el tipo real de un archivo por su firma binaria, no por su extensión."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'har-viewer';
